### PR TITLE
Pokémon Green's Cerulean Cave blk

### PR DESCRIPTION
**Pull request by 95girl**

### CODE REVIEW

**Comment by mid-kid** [comment]
While these are nice to have, they don't represent content in the final game, and as such don't really fit in the repo. Consider putting/linking them on the wiki or just in a fork, instead.

**Comment by Rangi42** [comment]
I had suggested this in #298 because pokered also stores the alternate Green sprites and tilesets.

Although this PR would still need to get rid of the duplicate fourth file (which is causing the macOS build to fail anyway; I think because the filename is the same but case-changed).

**Comment by Rangi42** [comment]
Thanks @95girl . One more change please: put them in a `maps/green/` subdirectory, like how pokecrystal has `maps/unused/`. So `maps/green/CeruleanCave1F.blk` instead of `maps/CeruleanCave1FGreen.blk`, and so on.

**Comment by 95girl** [comment]
> Thanks @95girl . One more change please: put them in a `maps/green/` subdirectory, like how pokecrystal has `maps/unused/`. So `maps/green/CeruleanCave1F.blk` instead of `maps/CeruleanCave1FGreen.blk`, and so on.

https://github.com/95girl/pokered/tree/master/maps/green

like this?

**Comment by Rangi42** [comment]
Yes.

**Comment by Rangi42** [comment]
Superseded by #300.

**Pull request closed without merging**
