### PR TITLE
Add constants and table macros for the map sprite sets

### LINKED ISSUE #391: Add constants and table macros for the map sprite sets
The individual sprite sets use table macros to verify that they each have 11 sprites (9 walking and 2 still), but their IDs are still raw hex numbers.

- `$01`: Pallet Town, Viridian City, Cinnabar Island, Route 1, Route 2 (south), Route 20 (east), Route 21, Route 22
- `$02`: Pewter City, Cerulean City, Route 2 (north), Route 3, Route 4, Route 5 (north), Route 9, Route 10 (north), Route 24, Route 25
- `$03`: Lavender Town, Route 8 (west), Route 10 (south), Route 12 (north)
- `$04`: Vermilion City, Route 6 (south), Route 11 (east)
- `$05`: Celadon City, Route 7 (east), Route 16 (west)
- `$06`: Indigo Plateau, Route 23
- `$07`: Saffron City, Route 5 (south), Route 6 (north), Route 7 (west), Route 8 (east)
- `$08`: *[Silence Bridge]* Route 11 (west), Route 12 (south), Route 13, Route 14, Route 15 (west)
- `$09`: *[Cycling Road]* Route 16 (east), Route 17, Route 18 (east)
- `$0A`: Fuchsia City, Route 15 (east), Route 18 (west), Route 19, Route 20 (west)

### PR DESCRIPTION
**Pull request by Rangi42**
Fixes #391

### CODE REVIEW

**Comment by Rangi42** [comment]
@vulcandth Please review as well.

**Comment by Rangi42** [comment]
Note that this is simpler in Gen 2 since maps are divided into groups with outdoor sprite sets assigned per group, using a pointer table, and without split sets. (https://github.com/pret/pokecrystal/blob/master/data/maps/outdoor_sprites.asm)

**Review by vulcandth — APPROVED** [review]
Looks like an improvement to me! Didn't see anything that stood out to me.

**Comment by Rangi42** [comment]
`cp $f0` in engine/overworld/map_sprites.asm needs to be `cp FIRST_SPLIT_SET - 1`. Also `cp $f8` needs to be `cp SPLITSET_ROUTE_20`, and there are probably other weird hard-codings.

**Pull request merged**
