### PR TITLE
label hardcoded HRAM address, start documenting Vermilion

### PR DESCRIPTION
**Pull request by mattbruv**
Small change. was reading through the trash can code trying to understand it, and noticed a missing label for this address. May continue to clean up the vermilion city & gym code in the future.

### CODE REVIEW

**Comment by dannye** [comment]
Cool, thanks! Feel free to keep 'em coming. Do you want me to merge now, or leave it open for a little while for additional clean up?

**Comment by mattbruv** [comment]
Wait on it, I'll give a shot at cleaning up the whole file tomorrow. Are there guidelines as far as how to format labels, or when to use a local vs global label? In this case, I could have used either and the build would OK. Does it matter? Any info on contributing guidelines would be much appreciated.

**Comment by dannye** [comment]
pokered doesn't have a formal style guide.

Feel free to follow the general principles in this [style guide](https://github.com/pret/poketcg/blob/master/STYLE_GUIDE.md).
(It says to use `snake_case` for local labels, but pokered is not consistent. Your label of `.setFirstLockTrashCanIndex` is perfectly fine, and indeed what I think I have done in most cases.)

In general, if a label can be turned into a local label, then it probably should be.

**Comment by mattbruv** [comment]
@dannye I'm pretty happy with what I have here, it can be merged if you'd like. Probably won't document more for a while, as this took me longer than I expected.

**Comment by dannye** [comment]
Looks fantastic, thanks! The `.asm_xxxx` labels are one of the last remaining areas in need of clean up so it's very appreciated!

**Pull request merged**
