### PR TITLE
Map POKé in the assembler

### PR DESCRIPTION
**Pull request by iimarckus**
See https://github.com/pret/pokecrystal/pull/820

I did something slightly evil in this version. Unlike pokecrystal, where the literal string ‘P,’ ‘O,’ ‘K,’ ‘e’ only appears at its definition, pokered uses the full string in item names, trainer names, and the start menu. To keep them from getting wrongly translated to 0x54, I used a canonically equivalent Unicode string of “POKe + combining ´” instead of “POKé” for those words. RGBDS does not do canonically equivalent string comparisons so it doesn’t realize they’re the same.

### CODE REVIEW

**Comment by Rangi42** [comment]
I think that needing the literal sequence `P O K é` at all is a good reason to stick with `#` in all versions.

Polished Crystal does something like this—it maps a lot of common substring like "`the`" or "`ea`" or "`tr`" to single bytes for the sake of compression. However, just like pokered, some names, nicknames, etc need the real characters, so it has to maintain two charmaps, one without these sequences, and use `rawchar "Name@"` instead of `db "Name@"` for them.

This wouldn't be such a big deal in poke{red,yellow,gold,crystal}, since this is the only string that would get such treatment. However, I expect it could cause more confusion than it resolves, if people type `POKé` expecting four bytes and get one, or use it in a context where special characters don't get handled (IIRC there are some).

Having "`#`" map to $54 makes it clear that something is special about that character, and users should eventually note how home/text.asm expands certain sequences anyway (like turning the "`<PLAYER>`" byte into the contents of `wPlayerName`). The charmap.asm could have comments to that effect, like how so many constant enums and data tables do.

**Comment by dannye** [comment]
If pokered were as clean as pokecrystal is where *all* instances of `POKé` are 1 byte instead of 4 (other than the instance in the text processor code), I think this might be worth it.
But given that it's a mixed bag, I think it's important for it to be clear which is which. If we were to give `#` a better name, I might consider something like `<POKé>` to make it clear that it is still a special character, and to be consistent with other character mappings, like `<PKMN>`.

Another concern is people may try to lowercase instances of "POKé" rather than change the charmap entry.
They may change `"POKéMON LEAGUE@"` to `"Pokémon League@"` and now they've unknowingly made the text 3 bytes longer.

**Comment by aaaaaa123456789** [comment]
I'd say that anything that relies on invisible differences in the code is an instant 'no'. There's simply no two ways around that. There's a good reason why `;` (which is in fact not a semicolon, but U+037E GREEK QUESTION MARK) is a meme and often referred to as a prank.

But let's pretend there's something better than denormalized Unicode for this. (Well, there are definitely better options out there, so it's not really pretending.) Is this really a good idea? `#` is replaced by `POKé` by the text engine, but it's just a random bogus character if you manage to actually get it on screen (e.g., by writing data directly to the tilemap). If anyone actually copies a string without invoking the text engine, any text containing "POKé" will instantly break, and the fix is both unintuitive and extremely ugly. This is not a newbie trap — this is an everyone trap.

I think this is a really, really bad idea. Even for repos where the solution is cleaner, such as pokecrystal.

**Comment by iimarckus** [comment]
Well, obviously I disagree.

> Having "#" map to $54 makes it clear that something is special about that character

That is already common. Aside from `<PLAYER>` etc., even simple things like `'s` map multiple input characters to a single byte—even more confusingly (to the unaware), to a single tile.

> I expect it could cause more confusion than it resolves

In *this* codebase? New users are already blasted with such a huge wave of new concepts already, this is hardly going to tip anyone over the edge, especially since other magic text strings exist already.

> Another concern is people may try to lowercase instances of "POKé" rather than change PlacePOKeText:: db "POKé@".

Lowercasing is already nontrivial because of strings like Pokédex, Pokémaniac, Poké Ball, Pokémon line‐wrapped with a hyphen—and, as everyone has so eloquently reminded me, the cases of POKé that aren’t $54 internally. Compared to that, this is an improvement: POKé is easier to search for than # and the spelled‐out exceptions are few enough to document easily.

If that’s too confusing, make a wiki page. We already have documentation on [fixing design flaws](https://github.com/pret/pokecrystal/blob/master/docs/design_flaws.md) and [fixing glitches](https://github.com/pret/pokecrystal/blob/master/docs/bugs_and_glitches.md) and [fixing hardcoded logic](https://github.com/pret/pokecrystal/wiki/Hard-coded-logic). Considering how popular lowercasing is already, we should have a page for it anyway… and I guarantee eliminating `#` will make it shorter.

> They may change `"POKéMON LEAGUE@"` to `"Pokémon League@"` and now they've unknowingly made the text 3 bytes longer.

I was concerned about this too, so I tested expanding every string in the ROM this way, and saw no negative effects. There are many other things that make data subtly longer with worse effects (like pics). In contrast this is really not a problem.

> But let's pretend there's something better than denormalized Unicode for this. (Well, there are definitely better options out there, so it's not really pretending.)

I’m all ears.

**Comment by Pokechu22** [comment]
How about `<POKé>` like `<PLAYER>`?

**Comment by Rangi42** [comment]
Nobody was really wanting to replace `#` with `<POKé>` on Discord either.

**Pull request closed without merging**
