### PR TITLE
Name UnusedCD40

### PR DESCRIPTION
**Pull request by Nog-Frog**
Every man deserves a name :)

### CODE REVIEW

**Comment by dannye** [comment]
Can you elaborate on this change?

**Comment by Nog-Frog** [comment]
> Can you elaborate on this change?

UnusedCD40 is used in engine/menu/main_menu.asm.
It holds the x position for the cursor on the 'Cancel' option in the 'Options' menu.
The game loads 1 into it at [Line 459](https://github.com/pret/pokered/blob/master/engine/menu/main_menu.asm#L462), and then reads from it at [Line 543] (https://github.com/pret/pokered/blob/master/engine/menu/main_menu.asm#L545) (if Line 543 is called from line 528).

The name "UnusedCD40" no longer fits, since it IS used and now we know what for. :)

**Comment by dannye** [comment]
I'm not following. Line 528/542 does not appear to read from `UnusedCD40`.

**Comment by Sanqui** [comment]
In main_menu.asm, line 513 (https://github.com/pret/pokered/blob/master/engine/menu/main_menu.asm#L513):
`	ld hl, wOptionsTextSpeedCursorX ; $cd3d`
it then proceeds to call `.updateMenuVariables` four times and `inc hl` between them.  Hence it uses `cd3d`, `cd3e`, `cd3f`, and the `cd40` in question, which has been previously named Unused.

**Comment by dannye** [comment]
Oh, I see now. I should have looked more closely.
Perhaps `wUnusedCD3D` from the Hall of Fame PC menu is used the same way?

**Comment by Nog-Frog** [comment]
Not sure, but, will this PR be merged?
Are there any changes required before it is?

**Pull request merged**
