### PR TITLE
Fix floating sections

### PR DESCRIPTION
**Pull request by AntonioND**
This is needed to prevent rgblink from moving them around in future
releases.

I haven't had time to test this, though...

### CODE REVIEW

**Comment by AntonioND** [comment]
In case someone wonders why: https://github.com/rednex/rgbds/issues/136

**Comment by AntonioND** [comment]
Ok, no, there are still a lot of sections that aren't ordered correctly...

**Comment by AntonioND** [comment]
Now it compiles to the same md5.

**Comment by Sanqui** [comment]
Builds and matches under both rgbds 0.2.4 and master.  Thank you!

**Pull request merged**
