### PR TITLE
Rename `EV_*` constants to `EVOLVE_*` like pokecrystal

### PR DESCRIPTION
**Pull request by SatoMew**
I changed the constants to match pokegold and pokecrystal, and updated the remaining instances of the level-based evolution type.

### CODE REVIEW

**Comment by dannye** [comment]
The 1's that you replaced do not represent `EV_LEVEL`, they are the minimum level requirement for the `EV_ITEM` evolution that they are a part of.
https://github.com/pret/pokered/blob/master/engine/pokemon/evos_moves.asm#L102

**Comment by SatoMew** [comment]
oh, my apologies, I misunderstood what they represented.

**Comment by Rangi42** [comment]
Thanks! This is a good start toward syncing gen 1 and 2 evos/attacks data, but should we leave this PR open to do more? For example, decide on one name (evos_attacks.asm or evos_moves.asm?), and consistent comments (`; Evolutions` and `; Learnset` headers, or `; no more evolutions` and `; no more level-up moves` trailers?). Ideally a diff of the pokered and pokecrystal files would show the actual changes in game data, not asm formatting differences.

**Comment by SatoMew** [comment]
> Thanks! This is a good start toward syncing gen 1 and 2 evos/attacks data, but should we leave this PR open to do more?

I'm OK with that! 🙂

**Comment by Rangi42** [comment]
This is not being maintained, so merging as-is, just for the small pokecrystal sync.

**Pull request merged**
