### PR TITLE
Labeling remaining wram addresses

### PR DESCRIPTION
**Pull request by vulcandth**
This is the start of labeling the remaining wram addresses.. I'll be working on this in the next few days. Feel free to review as I work.

Just gonna toss all these misc flag constants in wram\_constants.asm for now. We can sort them elsewhere later if it makes sense later.  
  
Also, instead of trying to come up with a single wram label for an address whose bits are used for different things... I'm going to opt to just specify multiple labels for the same address.

- [x]  wd72e
- [x]  wd72d
- [ ]  wd732
- [ ]  wUnusedCF8D
- [ ]  wd736
- [ ]  wUnusedCD39
- [ ]  wFlags_D733
- [ ]  wUnusedCD37
- [ ]  wUnusedD08A
- [ ]  wUnusedD119
- [x]  wd728
- [ ]  wUnusedD71B
- [ ]  wd11e
- [ ]  wUnusedD71F
- [ ]  wcd6d
- [ ]  wUnusedCD3D
- [ ]  wUnusedCD3A
- [ ]  wd0b5
- [ ]  wUnusedCC5B
- [ ]  wUnusedD366
- [ ]  wUnusedD09B
- [ ]  wUnusedD153
- [ ]  wFlags_0xcd60
- [ ]  wUnusedD5A3
- [ ]  wcf91
- [ ]  wUnusedDA38
- [ ]  wUnusedC000
- [ ]  wd72c
- [x]  wd730

### CODE REVIEW

**Comment by Vortyne** [comment]
what about `wUnknownSerialCounter` and `wUnknownSerialCounter2`

**Comment by vulcandth** [comment]
> what about `wUnknownSerialCounter` and `wUnknownSerialCounter2`

I have a vendetta against them.

**Comment by vulcandth** [comment]
> what about `wUnknownSerialCounter` and `wUnknownSerialCounter2`

I'm saving those for you to do.

**Comment by Rangi42** [comment]
Superseded by #454. (Which could use review/comments based on this though!)

**Pull request closed without merging**
