### PR TITLE
Move more tables from engine/ to data/

### PR DESCRIPTION
**Pull request by Rangi42**
This also splits the end of engine/battle/core.asm into engine/battle/effects.asm (similar to pokecrystal's effect_commands.asm; since core.asm was 191 KB, the largest code file in pokered).

I expect @TheFakeMateo to be making a reorganization PR in the future which would, among other things, add more subdirectories to engine/ and data/, so there wouldn't be this long flat list of unsorted data files. (Like pokecrystal, with data/tilesets, data/items, etc.)

### CODE REVIEW

**Comment by TheFakeMateo** [comment]
Yeah, as @Rangi42 mentioned, I've been doing some restructuring on one of my projects to intentionally bring it more in line with pokecrystal's organization, and the plan was to come up with a PR for vanilla pokered after I get my hack's repo settled in, and after I discuss everything with @dannye

**Comment by dannye** [comment]
Good stuff, thanks. Do you think some of the new files in `data/` would actually be better in `data/battle/`? (Like the move and trainer related files.)

Either way, looks really good.

**Comment by Rangi42** [comment]
I'm anticipating data/moves/ and data/trainers/, as well as data/pokemon/, data/maps/, data/tilesets/, data/items/, and any other data/*foo*/ subdirs for grouping many *foo*-related files.

**Comment by dannye** [comment]
Makes sense. Thanks.

**Pull request merged**
