### PR TITLE
Use the same music headers as pokecrystal

### PR DESCRIPTION
**Pull request by Rangi42**

### CODE REVIEW

**Comment by dannye** [comment]
While I'm not against this change, for the record I suggested [here](https://github.com/pret/pokecrystal/issues/556#issuecomment-515690709) that pokecrystal could adopt pokered's header format but no one weighed in on that suggestion. Since we were discussing making the header shorter and less redundant.
I still kind of like the 1-line header, although I admit it removes some freedom with label names. But at the same time, when would a song need non-uniform channel labels?

**Comment by Rangi42** [comment]
I dislike the `audio_header` macro because, not only does it auto-generate the channels' label names, but it relies on constants that share the names of the label suffixes (`Ch1`, `Ch2`, etc, instead of `CHAN1`, `CHAN2`, etc).

In pokecrystal I can open an audio file, double-click one of the labels in its header, and jump to the definition of that channel.

**Comment by Rangi42** [comment]
Actually, what about simplifying it even more?

```
Music_PalletTown::
	audio_channels Music_PalletTown, 1, 2, 3

SFX_Cry00_1::
	audio_channels SFX_Cry00_1, 5, 6, 8
```

This avoids the need for precisely-named `Ch1`, `Ch2`, etc constants, and makes the channel values obviously numeric. It does still involve auto-generated labels, but then again, so does tileset_headers.asm (`tileset Overworld, ...` has `dw \1_Block, \1_GFX, \1_Coll`).

**Comment by dannye** [comment]
> I dislike the `audio_header` macro because, not only does it auto-generate the channels' label names, but it relies on constants that share the names of the label suffixes (`Ch1`, `Ch2`, etc, instead of `CHAN1`, `CHAN2`, etc).

👍 

> In pokecrystal I can open an audio file, double-click one of the labels in its header, and jump to the definition of that channel.

Yeah, admittedly, I've been relying on this a lot lately and would be bummed to lose this ability.

> (Also, at one point we got rid of the "header" terminology for maps, music, menus, cries, etc, because they aren't technically required to be at the head of the actual data, and some things even have more than one "header" (map_header_2.asm) where it's just another set of broken-up data.)

Eh, I don't have an issue with "header" terminology in cases like this where the "header" must come (logically) before the data.


All in all, I'm good with this PR as-is and leaving pokecrystal alone. Just wanted to revisit that thread from before to be sure.

**Review by dannye — APPROVED** [review]

**Review by mid-kid — APPROVED** [review]
I like this change.

**Pull request merged**
