### PR TITLE
Rename unknownsfx0x20, unknownsfx0x10 and unknownnoise0x20

### PR DESCRIPTION
**Pull request by Eggy0**
Through personal experimentation, I discovered what unknownsfx0x20, unknownsfx0x10 and unknownnoise0x20 do. Namely, two of them are for generating a sound/note and one is an effect that modifies how they sound, so in my fork I've renamed them accordingly (squarenote, pitchenvelope and noisenote, respectively).

### CODE REVIEW

**Comment by dannye** [comment]
Thanks for this. I think you're absolutely right about pitchenvelope.

When I originally documented all this stuff and named the macros, I didn't know anything about hardware sound registers
But taking another look at it, it looks like pitchenvelope just writes to rNR10 which basically takes two parameters packed into one byte.
The first parameter is the duration of the effect (0-7) the second parameter is the pitch shift (-7 to 7)

The macro is currently
```
pitchenvelope: MACRO
	db $10
	db \1
ENDM
```

But I think it should be changed to:
```
pitchenvelope: MACRO
	db $10
	IF \2 > 0
		db (\1 << 4) | \2
	ELSE
		db (\1 << 4) | (%1000 | (\2 * -1))
	ENDC
ENDM
```

Then the use of the pitchenvelope macro could change from this:
```
pitchenvelope 58
```

To this:
```
pitchenvelope 3, -2
```

Since 58 in hex is $3A, and $A is %1010 (-2 for the case of rNR10)

I'll do this right now.

Thanks again.

**Comment by dannye** [comment]
https://github.com/pret/pokered/commit/b382473f7b6827020f5544c8dcc730be8fc83f6e

@Eggy0 
If you think you are able to help figuring out the exact format for the parameters for squarenote and noisenote, feel free to comment

Currently, squarenote takes 4 parameters and noisenote takes 3
But taking another look, I think the last two parameters for squarenote should be considered one 16 bit parameter (little-endian). In both cases it represents the frequency.

For both squarenote and noisenote, I think the first parameter is the duty.

I think the second parameter is the volume sweep (similar to pitch sweep), so I think it needs to be broken up into two parameters; initial volume (0 to 15) and volume shift (-7 to 7)

So considered what we have currently:
```
squarenote 3, 196, 129, 6
```
3 is the duty.
196 is the volume sweep, which in hex is $C4, which means an initial volume of 12 and volume shift of +4.
129 and 6 I think should actually be the 16 bit value 6 * $100 + 129 = 1665

Then it would become:
```
squarenote 3, 12, 4, 1665
```


The macro definition is currently:
```
squarenote: MACRO
	db $20 | \1
	db \2
	db \3
	db \4
ENDM
```

I think it should become:
```
squarenote: MACRO
	db $20 | \1
	IF \3 > 0
		db (\2 << 4) | \3
	ELSE
		db (\2 << 4) | (%1000 | (\3 * -1))
	dw \4
ENDM
```
Similar change to noisenote except \4 is a byte, not a word.

I haven't tested any of this yet, just thinking out loud.

**Comment by Eggy0** [comment]
Actually, for squarenote, the 3 is actually length and not duty. Duty is set seperately through the aptly named "duty" command. 12 is the volume sweep as you specified, and from what I see 129 and 6 are pitch and octave, respectively. Seeing the new commits, although I haven't played with them yet, I feel like the ones for frequency are now needlessly complicated to edit as one parameter set the pitch (e.g. C, D, #A etc.) with a number from 0 to 255 and the other set the octave with a single digit number, and like this it would likely take some calculation and/or a lot of trial and error just to get one note to sound as desired. With the previous format one would only need to change one parameter to something slightly bigger or smaller for fine tuning instead of possibly having to calculate their new value each time before typing it in. Correct me if I'm wrong.
While I haven't tested noisenote as much, I think its parameter format is the same as squarenote - minus the octave parameter.

**Comment by bitman44** [comment]
I doubt the 6 is octave control. I'd assume that the values for each note are loaded directly into the [sound control registers](http://gbdev.gg8.se/wiki/articles/Gameboy_sound_hardware#Registers). Square 1 is defined like this:

    NR10 FF10 -PPP NSSS Sweep period, negate, shift
    NR11 FF11 DDLL LLLL Duty, Length load (64-L)
    NR12 FF12 VVVV APPP Starting volume, Envelope add mode, period
    NR13 FF13 FFFF FFFF Frequency LSB
    NR14 FF14 TL-- -FFF Trigger, Length enable, Frequency MSB

The 12 and 4 would be stored in NR12 as $C4, and the 129 and 6 would be stored in NR13 and NR14 as $81 and $06. The gameboy would read this as frequency $681, or 1665 Hz, which is G#6. It makes sense for all notes to be defined with pitch like this, because otherwise those frequencies would need to be generated in realtime and the Gameboy isn't built for fast floating-point multiplication.

**Comment by dannye** [comment]
@Eggy0 
You're right about the first parameter being length and not duty. Thanks.

@bitman44 
I made a list of all unique frequencies that appear with squarenote (I didn't include frequencies with noisenote) and there are 245 frequencies used.
That's already annoying because if there are theoretically a maximum of 8 octaves each with 12 notes, then there should be a maximum of 96 notes, if each frequency landed right on a note.

And assuming the frequency values do correspond to real frequencies the way we would expect (like you said 1665 would be approximately G#6) then 222 of the 245 frequencies that appear lie between C6 and C7

So I'm thinking that for squarenote and noisenote it is probably not practical to come up with a list of constants or some other way to represent the macro arguments any prettier than they are currently.

**Comment by bitman44** [comment]
@dannye Yeah, that did strike me as weird, but I looked at the audio engine files and at the end, there's a lookup table for the 12 semitones:

    Audio1_Pitches:
        dw $F82C ; C_
        dw $F89D ; C#
        dw $F907 ; D_
        dw $F96B ; D#
        dw $F9CA ; E_
        dw $FA23 ; F_
        dw $FA77 ; F#
        dw $FAC7 ; G_
        dw $FB12 ; G#
        dw $FB58 ; A_
        dw $FB9B ; A#
        dw $FBDA ; B_

This makes me think that the pitch is only specified by frequency for sound effects, whereas for music the pitch is determined by looking at this lookup table for the note and then shifting the 2-byte value left or right to change the octave. So having most of the instances of the macro being between C6 and C7 just means that most sound effects are in that octave.

**Pull request merged**
